papillon_all_users:
    pattern:  /users
    defaults: { _controller: ApiRestBundle:User:all, _format: json }
    requirements:
        _method: GET

papillon_one_user:
    pattern:  /users/{id}
    defaults: { _controller: ApiRestBundle:User:get, _format: json }
    requirements:
        _method: GET
        id: "\d+"

papillon_all_tasks:
    pattern:  /tasks
    defaults: { _controller: ApiRestBundle:Task:all, _format: json }
    requirements:
        _method: GET

papillon_all_projects:
    pattern: /projects
    defaults: { _controller: ApiRestBundle:Projects:all, _format: json }
    requirements:
        _method: GET

papillon_all_client:
    pattern: /customers
    defaults: { _controller: ApiRestBundle:Customer:all, _format: json }
    requirements:
        _method: GET

