api_rest:
    type : rest
    resource: "@ApiRestBundle/Resources/config/routing.yml"
    prefix:   /api

papillon_tasks:
    resource: "@PapillonTasksBundle/Resources/config/routing.yml"
    prefix:   /

papillon_login:
    resource: "@PapillonUserBundle/Resources/config/routing.yml"

PapillonUserBundle:
    resource: "@PapillonUserBundle/Controller/"
    type: annotation
    prefix: /

PapillonTasksBundle:
    resource: "@PapillonTasksBundle/Controller/"
    type: annotation
    prefix: /