api_rest:
    type : rest
    resource: "@ApiRestBundle/Resources/config/routing.yml"
    prefix:   /api

NelmioApiDocBundle:
    resource: "@NelmioApiDocBundle/Resources/config/routing.yml"
    prefix:   /api/doc

papillon_login:
    resource: "@PapillonUserBundle/Resources/config/routing.yml"

papillon_tasks:
    resource: "@PapillonTasksBundle/Resources/config/routing.yml"
    prefix:   /

PapillonTasksBundle:
    resource: "@PapillonTasksBundle/Controller/"
    type: annotation
    prefix: /

fos_js_routing:
    resource: "@FOSJsRoutingBundle/Resources/config/routing/routing.xml"