security:
    encoders:
        Papillon\UserBundle\Entity\User: sha512
    providers:
        user:
            entity: { class: PapillonUserBundle:User }

    role_hierarchy:
        ROLE_ADMIN:       ROLE_USER
        ROLE_SUPER_ADMIN: [ROLE_USER, ROLE_ADMIN, ROLE_ALLOWED_TO_SWITCH]

    firewalls:
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js|fonts)/
            security: false

        main:
            pattern:    ^/
            anonymous: ~

            form_login:
                login_path: signin
                check_path: login_check
                default_target_path: /dashboard/home
                always_use_default_target_path: true
                use_referer: true
                post_only: true

            logout:
                path: signout
                target: signin

            remember_me:
                key:      "%secret%"
                lifetime: 31536000 # 365 days in seconds
                path:     /
                domain:   ~ # Defaults to the current domain from $_SERVER

    access_control:
        - { path: ^/signup$, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/signin$, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/, role: [ROLE_USER, ROLE_PLAYER] }
        #- { path: ^/admin, roles: ROLE_ADMIN }
        #- { path: ^/secure, roles: IS_AUTHENTICATED_ANONYMOUSLY, requires_channel: https }
        #- { path: ^/_internal, roles: IS_AUTHENTICATED_ANONYMOUSLY, ip: 127.0.0.1 }
