<?php

namespace Papillon\TasksBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * CustomersRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CustomersRepository extends EntityRepository
{
}
