<?php

namespace Papillon\TasksBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * TasksRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TasksRepository extends EntityRepository
{

    public function getTasksByUser($assigned_to)
    {
        $qb = $this->createQueryBuilder('t')
            ->orderBy('t.created_at', 'DESC');

        if($assigned_to){
           // $qb->where('t.addedBy = :addedBy')->setParameter('addedBy', $assigned_to);
        }

        $query = $qb->getQuery();
        return $query->getResult();
    }

}
