Papillon\UserBundle\Entity\User:
    type:  entity
    table: fos_user
    id:
        id:
            type: integer
            generator:
                strategy: AUTO
    fields:
        first_name:
            type: string
            length: '80'
        last_name:
            type: string
            length: '80'