homepage:
    path:     /
    defaults: { _controller: PapillonTasksBundle:Dashboard:index }

list_tasks:
    pattern:  /tasks/list.{_format}
    defaults: { _controller: PapillonTasksBundle:Task:list , _format: ~ }
    requirements:
          _method: GET


